# Generated by Django 3.2.8 on 2023-10-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='distance',
            field=models.TextField(default=0, verbose_name='距离'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='space',
            field=models.CharField(default=0, max_length=100, verbose_name='地点'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='speed',
            field=models.TextField(default=0, verbose_name='速度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='used_time',
            field=models.TextField(default=0, verbose_name='用时'),
            preserve_default=False,
        ),
    ]
