# Generated by Django 3.2.8 on 2023-10-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20231005_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.TextField(default=0, verbose_name='喜欢'),
            preserve_default=False,
        ),
    ]
