# Generated by Django 3.2.8 on 2023-10-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='username',
            field=models.TextField(default=11, verbose_name='用户名'),
            preserve_default=False,
        ),
    ]
