# Generated by Django 3.2.8 on 2023-10-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
