# Generated by Django 3.2.8 on 2023-10-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='post_id',
            field=models.TextField(default=1, verbose_name='用户id'),
            preserve_default=False,
        ),
    ]
