# Generated by Django 3.2.8 on 2023-10-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_comment_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='nickname',
            field=models.TextField(default=111, verbose_name='名称'),
            preserve_default=False,
        ),
    ]
