# Generated by Django 3.2.8 on 2023-10-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='history',
            name='used_time',
        ),
        migrations.AddField(
            model_name='history',
            name='calorie',
            field=models.IntegerField(default=0, verbose_name='总卡路里'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='step',
            field=models.IntegerField(default=0, verbose_name='总步数'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='distance',
            field=models.IntegerField(verbose_name='总距离'),
        ),
    ]
