# Generated by Django 3.2.8 on 2023-10-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20231009_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='calorie',
            field=models.IntegerField(default=0, verbose_name='总卡路里'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='distance',
            field=models.IntegerField(default=0, verbose_name='总距离'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='step',
            field=models.IntegerField(default=0, verbose_name='总步数'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='history',
        ),
    ]
