# Generated by Django 3.2.8 on 2023-10-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20231009_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.TextField(default=1, verbose_name='文章id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='post_id',
            field=models.TextField(verbose_name='文章id'),
        ),
    ]
