# Generated by Django 3.2.8 on 2023-10-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20231015_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='calorie',
            field=models.FloatField(verbose_name='总卡路里'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='distance',
            field=models.FloatField(verbose_name='总距离'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='step',
            field=models.FloatField(verbose_name='总步数'),
        ),
    ]
